#!/bin/bash

# Script to create distribution tarballs for multiple platforms
# Usage: ./make-dist.sh [VERSION]

VERSION=${1:-$(cat VERSION 2>/dev/null || echo "1.0.0")}
PROJECT_NAME="http-loadbalancer"
TARBALL="${PROJECT_NAME}-${VERSION}.tar.gz"
ZIPFILE="${PROJECT_NAME}-${VERSION}.zip"

echo "Creating distribution packages for version ${VERSION}..."
echo ""

# Get the directory name
DIRNAME=$(basename "$(pwd)")
PARENT=$(dirname "$(pwd)")

# Create a temporary directory for the distribution
TMPDIR=$(mktemp -d)
DISTDIR="${TMPDIR}/${PROJECT_NAME}-${VERSION}"

echo "Copying files to temporary directory..."

# Create directory structure
mkdir -p "${DISTDIR}"

# Copy files (exclude build artifacts, git files, etc.)
# Note: We exclude root-level config.h (generated by configure) but keep include/config.h (source file)
rsync -a --exclude='.git' \
         --exclude='build' \
         --exclude='server.log' \
         --exclude='config' \
         --exclude='*.o' \
         --exclude='Makefile' \
         --exclude='/config.h' \
         --exclude='config.log' \
         --exclude='config.status' \
         --exclude='autom4te.cache' \
         --exclude='*.tar.gz' \
         --exclude='*.tar.bz2' \
         --exclude='*.zip' \
         --exclude='.DS_Store' \
         --exclude='make-dist.sh' \
         --exclude='build-windows.sh' \
         . "${DISTDIR}/"

# Update VERSION file
echo "${VERSION}" > "${DISTDIR}/VERSION"

# Create .tar.gz (Linux/Mac/Unix)
echo "Creating ${TARBALL}..."
cd "${TMPDIR}"
tar -czf "${TARBALL}" "${PROJECT_NAME}-${VERSION}"

# Create .zip (Windows/Cross-platform)
echo "Creating ${ZIPFILE}..."
zip -rq "${ZIPFILE}" "${PROJECT_NAME}-${VERSION}"

# Move to original location
mv "${TARBALL}" "${PARENT}/"
mv "${ZIPFILE}" "${PARENT}/"

# Cleanup
rm -rf "${TMPDIR}"

echo ""
echo "Distribution packages created:"
echo "  - ${PARENT}/${TARBALL} (Linux/Mac/Unix)"
echo "  - ${PARENT}/${ZIPFILE} (Windows/Cross-platform)"
echo ""
echo "To test the distribution:"
echo "  Linux/Mac:"
echo "    cd /tmp"
echo "    tar -xzf ${PARENT}/${TARBALL}"
echo "    cd ${PROJECT_NAME}-${VERSION}"
echo "    ./configure && make"
echo ""
echo "  Windows:"
echo "    Extract ${ZIPFILE}"
echo "    See BUILD-WINDOWS.md for instructions"
